"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil

import pytest


@pytest.mark.skipif(
    shutil.which("scitex-dev") is None,
    reason="scitex-dev not installed — add `scitex-dev[cli-audit]` to [project.optional-dependencies.dev]",
)
def test_audit_all_clean():
    # Arrange
    from scitex_dev.testing import audit_all_for_package

    # Act
    result = audit_all_for_package('scitex-resource')

    # Assert — audit_all_for_package returns None on a clean
    # audit and raises AssertionError on any unexpected finding,
    # so reaching this point with result is None means clean.
    assert result is None
